export const items = [
  {
    id: 1,
    title: "Стул серый",
    img: "chair-grey.jpeg",
    desc: "Производитель: Китай. Размер: 44x86x54см.",
    category: "chairs",
    price: "49.99",
  },
  {
    id: 2,
    title: "Стол",
    img: "table.webp",
    desc: "Производитель: Россия. Размер: 120x77x54см.",
    category: "table",
    price: "149.00",
  },
  {
    id: 3,
    title: "Диван",
    img: "sofa.jpeg",
    desc: "Производитель: Россия. Размер: 225x90x95см.",
    category: "sofa",
    price: "549.99",
  },
  {
    id: 4,
    title: "Лампа",
    img: "wall-light.jpeg",
    desc: "Производитель: Китай. Размер: 13x26x13см.",
    category: "light",
    price: "25.00",
  },
  {
    id: 5,
    title: "Стул белый",
    img: "chair-white.jpeg",
    desc: "Производитель: Китай. Размер: 44x86x54см.",
    category: "chairs",
    price: "49.99",
  },
  {
    id: 6,
    title: "Стол лофт",
    img: "table-loft.jpg",
    desc: "Производитель: Китай. Размер: 120x74x60см.",
    category: "table",
    price: "189.99",
  },
];
